dataset:
  name: "LapSRN"
  type: "super-resolution"
  parameters:
    paths:
      train:
        - presets/data/LapSRN/train
        - ["png", ]
      test:
        - presets/data/LapSRN/test
        - ["png", ]
    downscale_factor: 2
    downscale_method: "nearest"